version: 2

jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            sudo apt update
            sudo apt install -y wget python3-pip
            pip install requests
      - run:
          name: Download latest build of Source.Python
          command: |
            python3 download_sp.py source-python/
            unzip source-python/source-python.zip -d source-python/
            rm source-python/source-python.zip
          working_directory: ~/project/
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=csgo-server-python -t csgo-server-python .
          no_output_timeout: 30m
      - deploy:
          name: Push application Docker image
          command: |
            version=$(git describe --abbrev=0)
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag csgo-server-python $DOCKER_USER/csgo-server-python:$version
            docker push $DOCKER_USER/csgo-server-python:$version

workflows:
  version: 2
  build:
    jobs:
      - build