version: 2

jobs:
  download_sp:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/csgo-server-python
    steps:
      - checkout
      - run: |
            python3 -m venv venv
            . venv/bin/activate
            pip install requests
            python download_sp.py source-python/
            unzip source-python/source-python.zip -d source-python/
            rm source-python/source-python.zip
      - persist_to_workspace:
          root: .
          paths: source-python
  build_server:
    machine:
      image: circleci/classic:latest
    working_directory: ~/csgo-server-python
    steps:
      - checkout
      - attach_workspace:
          at: ~/csgo-server-python
      - run:
          name: Build application Docker image
          command: |
            docker build -t csgo-server-python .
          no_output_timeout: 30m
      - deploy:
          name: Push application Docker image
          command: |
            version=$(git describe --abbrev=0)
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag csgo-server-python $DOCKER_USER/csgo-server-python:$version
            docker tag csgo-server-python $DOCKER_USER/csgo-server-python:latest
            docker push $DOCKER_USER/csgo-server-python:$version
            docker push $DOCKER_USER/csgo-server-python:latest

workflows:
  version: 2
  un-tagged-build:
    jobs:
      - download_sp:
          filters:
            tags:
              ignore: /^.*/
      - build_server:
          requires:
            - download_sp
          filters:
            tags:
              ignore: /^.*/
  tagged-build:
    jobs:
      - download_sp:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/`
      - build_server:
          requires:
            - download_sp
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^.*/
