version: 2
jobs:
  build:
    working_directory: /csgo-server-python
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/csgo-server-python.tar
      - run:
          name: Update Source.Python
          command: |
            git submodule update --init --recursive
      - run:
          name: Build Source.Python
          command: |
            cd Source.Python/src/
            chmod a+x Build.sh
            /bin/bash/ ./Source.Python/src/Build.sh csgo
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/csgo-server-python.tar | true
          no_output_timeout: 20m
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=csgo-server-python -t csgo-server-python .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/csgo-server-python.tar csgo-server-python
          no_output_timeout: 20m
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/csgo-server-python.tar
      - deploy:
          name: Push application Docker image
          command: |
            echo $DOCKER_USER
            echo $DOCKER_PASS
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag csgo-server-python $DOCKER_USER/csgo-server-python
            docker push $DOCKER_USER/csgo-server-python
