version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - ${CACHE_VERSION}-{{ .Branch }}
          paths:
            - ~/caches/csgo-server-python.tar
      - run:
          name: Install requirements
          command: |
            sudo apt update
            sudo apt install -y wget
      - run:
          name: Update Source.Python
          command: |
            git submodule update --init
          working_directory: ~/project/
      - run:
          name: Download latest build of Source.Python
          command: |
            wget 'http://builds.sourcepython.com/job/Source.Python%20-%20Building/game=csgo,label=master/lastSuccessfulBuild/artifact/src/Builds/Linux/csgo/*zip*/csgo.zip'
            unzip csgo.zip
            mv csgo/core.so ~/project/Source.Python/addons/source-python/bin/
            mv csgo/source-python.so ~/project/Source.Python/addons/
          working_directory: builds
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i ~/caches/csgo-server-python.tar | true
          no_output_timeout: 20m
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=csgo-server-python -t csgo-server-python .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p ~/caches
            docker save -o ~/caches/csgo-server-python.tar csgo-server-python
          no_output_timeout: 20m
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/caches/csgo-server-python.tar
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag csgo-server-python $DOCKER_USER/csgo-server-python
            docker push $DOCKER_USER/csgo-server-python
