version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            sudo apt update
            sudo apt install -y wget
      - run:
          name: Update Source.Python
          command: |
            git submodule update --init
          working_directory: ~/project/
      - run:
          name: Download latest build of Source.Python
          command: |
            wget 'http://builds.sourcepython.com/job/Source.Python%20-%20Building/game=csgo,label=master/lastSuccessfulBuild/artifact/src/Builds/Linux/csgo/*zip*/csgo.zip'
            unzip csgo.zip
            mv csgo/core.so ~/project/Source.Python/addons/source-python/bin/
            mv csgo/source-python.so ~/project/Source.Python/addons/
          working_directory: builds
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=csgo-server-python -t csgo-server-python .
          no_output_timeout: 30m
      - deploy:
          name: Push application Docker image
          command: |
            version=$(git log -1 --pretty=%B)
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag csgo-server-python $DOCKER_USER/csgo-server-python:$version
            docker push $DOCKER_USER/csgo-server-python:$version
workflows:
  version: 2
  build:
    jobs:
      - build:
        filters:
          tags:
            only: /^[0-9]\.[0-9]\.[0-9]$/